### PR TITLE
Supported interface orientations fix

### LINKED ISSUE #398: SupportedInterfaceOrientations Horizontal fixed
As we all know we had problem with the supportedInterfaceOrientations property which doesn't take much effect.
I have fixed this issue by injecting the SIO property into the ActionSheetVC. 
https://github.com/moheny/ActionSheetPicker-3.0/tree/supportedInterfaceOrientations-fix

### PR DESCRIPTION
**Pull request by moheny**
This fixes #398

### CODE REVIEW

File: Pickers/SWActionSheet.m [hunk 1]
```diff
@@ -91,7 +92,9 @@ - (UIWindow *)window
             UIWindow *window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
             window.windowLevel        = self.windowLevel;
             window.backgroundColor    = [UIColor clearColor];
-            window.rootViewController = [SWActionSheetVC new];
+            SWActionSheetVC *new = [SWActionSheetVC new];
```
Comment (skywinder) [inline Pickers/SWActionSheet.m]: `new` is reserved name, sot lets use more related to this class name.

File: Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj [hunk 2]
```diff
@@ -502,6 +506,7 @@
 				ALWAYS_SEARCH_USER_PATHS = NO;
 				CLANG_ENABLE_OBJC_ARC = YES;
 				COPY_PHASE_STRIP = YES;
+				DEVELOPMENT_TEAM = M8UU7YPNPZ;
```
Comment (skywinder) [inline Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj]: please remove dev team from this PR

File: Pickers/SWActionSheet.m [hunk 3]
```diff
@@ -213,11 +223,14 @@ - (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interface
     return NO;
 }
 
-// iOS6 support
-// ---
 - (BOOL)shouldAutorotate
 {
-    return YES;
+    if (self.maskVC == UIInterfaceOrientationPortrait){
```
Comment (skywinder) [inline Pickers/SWActionSheet.m]: it could be realised easily

File: Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj (hunk 2 above)
Comment (moheny) [reply Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj]: Sorry for that.

File: Pickers/SWActionSheet.m (hunk 3 above)
Comment (moheny) [reply Pickers/SWActionSheet.m]: What do you mean? Can you please elaborate or suggest a better approach?

**Comment by moheny** [comment]
Hey can you please revisit?

**Comment by skywinder** [comment]
Dear @moheny , thank you very much for the stay in touch. 
I focused on other projects and doesn't work on this project last year.
I'm coming back to coding pretty soon. I will test it and release an update pretty soon.

Cheers 👍

**Comment by skywinder** [comment]
@moheny 
fyi: https://github.com/skywinder/ActionSheetPicker-3.0/issues/348

I would be glad to build a team of contributors. 
If you are actively using it this library -  I would be glad to make you collaborator as well.

**Comment by nimomix** [comment]
Looks good, when is this expected to be merged ?

**Comment by yoavkamary** [comment]
@skywinder is this going to be merged anytime soon? Thanks

**Comment by skywinder** [comment]
Hello everyone! Thank you for your patience! I'm back and will cleanup everything. Thank you very much for your contribution! 
I need help with future support. If anyone there is interested - please drop a comment here, please!
https://github.com/skywinder/ActionSheetPicker-3.0/issues/348

File: Pickers/SWActionSheet.h [hunk 4]
```diff
@@ -13,7 +13,9 @@
 
 - (void)showFromBarButtonItem:(UIBarButtonItem *)item animated:(BOOL)animated;
 
-- (instancetype)initWithView:(UIView *)view windowLevel:(UIWindowLevel)windowLevel;
+- (instancetype)initWithView:(UIView *)view windowLevel:(UIWindowLevel)windowLevel withSupportedOrientation:(UIInterfaceOrientationMask) mask;
```
Comment (skywinder) [inline Pickers/SWActionSheet.h]: please, do not change already existing init methind, otherwise we are loosing backward compatability. we have to make new one and make an alias to this.

File: Pickers/SWActionSheet.m (hunk 3 above)
Comment (skywinder) [reply Pickers/SWActionSheet.m]: Please, put it this way, so it makes the style more readable. it's just about good code style

**Comment by skywinder** [comment]
@moheny I added to comments, please, fix it or allow me to change this branch. ANd I will merge it soon! https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

File: Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj [hunk 5]
```diff
@@ -502,6 +503,7 @@
 				ALWAYS_SEARCH_USER_PATHS = NO;
 				CLANG_ENABLE_OBJC_ARC = YES;
 				COPY_PHASE_STRIP = YES;
+				DEVELOPMENT_TEAM = "";
```
Comment (skywinder) [inline Example Projects/ObjC-Example/ActionSheetPicker.xcodeproj/project.pbxproj]: Please, remove not related to this fix changes

File: Pickers/SWActionSheet.m [hunk 6]
```diff
@@ -213,11 +223,14 @@ - (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interface
...
+        return NO;
+    } else {
+        return YES;
+    }
+
```
Comment (skywinder) [inline Pickers/SWActionSheet.m]: more details about htis here:

https://wiki.c2.com/?ReturnBooleanEvaluations

```
This is a common idiom of just about every language, including Java.

Many programmers write methods that look like the following:

  public boolean isBigger() {
  // return if a is bigger than b
  if (a > b)
	return true;
  else
	return false;
  }


The if statement is redundant. Boolean expressions (a > b) evaluate to a boolean value -- if your method needs to return it, then there's no need to have an if statement. The following code is equivalent to the previous:

  public boolean isBigger () {
	// return if a is bigger than b
	return (a > b);
  }
```
