### PR TITLE
Fixed an issue building using the Swift Package Manager

### LINKED ISSUE #537: Not working with Swift Package Manager [bug]
If I use Cocoapod it is working

But if I use SPM I have an error:
Capture d’écran 2021-04-29 à 10 57 24

Module is correctly installed in SPM:
Capture d’écran 2021-04-29 à 10 58 21

The error is showing even after I cleaned and builded again

### PR DESCRIPTION
**Pull request by Econa77**
Fixed #537 
Related #542 

Changed the configuration of the project and header files for SPM.

### Checklist
- [x] Local Build
- [x] with CocoaPods
- [x] with SPM
- [x] with Carthage

### CODE REVIEW

File: CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetCustomPicker.h [hunk 1]
```diff
@@ -6,8 +6,14 @@
 //  Copyright (c) 2012 Club 15CC. All rights reserved.
 //
 #import <UIKit/UIKit.h>
-#import "AbstractActionSheetPicker.h"
-#import "ActionSheetCustomPickerDelegate.h"
+
```
Comment (Econa77) [inline CoreActionSheetPicker/CoreActionSheetPicker/Pickers/include/ActionSheetCustomPicker.h:9]:
```suggestion
```

**Review by noorulain17 — APPROVED** [review]
@Econa77 good work,
please squash your commits to one

**Comment by Econa77** [comment]
@noorulain17 Squashed 👍

**Review by noorulain17 — APPROVED** [review]
